import type { Experience } from "./types";

export const experiences: Experience[] = [
  {
    id: "gloria-fishcakes",
    title: "Make fishcakes with Gloria",
    host: "Gloria",
    parish: "St. Thomas",
    price: 15,
    duration: 30,
    description:
      "Gloria has run her stall for over 15 years. Pull up, learn how to season and fry a batch of a Bajan classic, then eat them hot from the pan.",
    shortDescription: "30 mins helping Gloria, then eat them hot",
    interests: ["food and drink", "history and heritage", "quiet and slow"],
    pace: "relaxed",
    accessibility: ["low physical exertion", "seated breaks available"],
    weeklyCapacity: 20,
    bookedThisWeek: 4,
    recentExposure: 0.18,
    rating: 4.8,
    reviews: 4,
    image: "/assets/gloria.jpg",
    reviewer: "Maya",
    reviewQuote:
      "Gloria was such a sweetheart and a great teacher. My fishcakes were delicious — it felt personal, not packaged."
  },
  {
    id: "janelle-pottery",
    title: "Pottery with Janelle",
    host: "Janelle",
    parish: "St. Philip",
    price: 22,
    duration: 60,
    description:
      "Sit at Janelle's small studio table, learn the basics of hand-building, and make a tiny keepsake inspired by island textures.",
    shortDescription: "A calm one-hour clay session in a tiny studio",
    interests: ["craft and making", "art and photography", "quiet and slow"],
    pace: "quiet",
    accessibility: ["seated activity"],
    weeklyCapacity: 12,
    bookedThisWeek: 3,
    recentExposure: 0.12,
    rating: 4.9,
    reviews: 7,
    image: "https://images.pexels.com/photos/4706135/pexels-photo-4706135.jpeg?auto=compress&cs=tinysrgb&w=1200",
    fallbackImage: "/assets/pottery.svg",
    reviewer: "Andre",
    reviewQuote: "Small, peaceful and exactly the kind of thing we would never have found on our own."
  },
  {
    id: "omar-garden",
    title: "Garden with Omar",
    host: "Omar",
    parish: "St. George",
    price: 12,
    duration: 45,
    description:
      "See cassava, herbs and ground provisions up close while Omar explains what grows well here and what ends up in his kitchen.",
    shortDescription: "A 45-minute garden walk with local growing stories",
    interests: ["nature and hikes", "food and drink", "history and heritage"],
    pace: "relaxed",
    accessibility: ["uneven ground"],
    weeklyCapacity: 18,
    bookedThisWeek: 5,
    recentExposure: 0.22,
    rating: 4.7,
    reviews: 9,
    image: "https://images.pexels.com/photos/32140331/pexels-photo-32140331.jpeg?auto=compress&cs=tinysrgb&w=1200",
    fallbackImage: "/assets/garden.svg",
    reviewer: "Sophie",
    reviewQuote: "Omar made every plant feel like part of a bigger Barbados story."
  },
  {
    id: "keisha-mahogany",
    title: "Woodcraft with Keisha",
    host: "Keisha",
    parish: "St. Michael",
    price: 18,
    duration: 50,
    description:
      "Step into Keisha's workshop for a short demonstration, then sand and finish a small piece while learning how she got into the craft.",
    shortDescription: "See a working craft studio and try a simple finishing step",
    interests: ["craft and making", "history and heritage", "art and photography"],
    pace: "relaxed",
    accessibility: ["standing optional", "hearing protection available"],
    weeklyCapacity: 10,
    bookedThisWeek: 2,
    recentExposure: 0.08,
    rating: 4.9,
    reviews: 2,
    image: "https://images.pexels.com/photos/7496747/pexels-photo-7496747.jpeg?auto=compress&cs=tinysrgb&w=1200",
    fallbackImage: "/assets/wood.svg",
    reviewer: "Daniel",
    reviewQuote: "The workshop was the highlight because it felt like meeting a person, not consuming an attraction."
  },
  {
    id: "popular-catamaran-cookout",
    title: "Coast cookout",
    host: "Island Day",
    parish: "St. Michael",
    price: 65,
    duration: 180,
    description:
      "A polished group cookout experience near the coast with a larger group format and a well-known operator.",
    shortDescription: "A high-demand three-hour group food experience",
    interests: ["food and drink", "fishing and sea"],
    pace: "active",
    accessibility: ["steps", "longer standing periods"],
    weeklyCapacity: 100,
    bookedThisWeek: 92,
    recentExposure: 0.94,
    rating: 4.9,
    reviews: 438,
    image: "https://images.pexels.com/photos/9629967/pexels-photo-9629967.jpeg?auto=compress&cs=tinysrgb&w=1200",
    fallbackImage: "/assets/coast.svg",
    reviewer: "Chris",
    reviewQuote: "Very organised and fun, but definitely a bigger tour experience."
  },
  {
    id: "marcus-rehearsal",
    title: "Rehearsal with Marcus",
    host: "Marcus",
    parish: "Christ Church",
    price: 10,
    duration: 40,
    description:
      "Drop into a small rehearsal, hear how a rhythm comes together, and ask Marcus about the music he grew up around.",
    shortDescription: "A low-key 40-minute rehearsal and conversation",
    interests: ["music and dance", "quiet and slow", "history and heritage"],
    pace: "quiet",
    accessibility: ["seated activity"],
    weeklyCapacity: 16,
    bookedThisWeek: 2,
    recentExposure: 0.15,
    rating: 4.8,
    reviews: 3,
    image: "https://images.pexels.com/photos/6270139/pexels-photo-6270139.jpeg?auto=compress&cs=tinysrgb&w=1200",
    fallbackImage: "/assets/music.svg",
    reviewer: "Nia",
    reviewQuote: "It felt like being invited in rather than sold a show."
  }
];
